# Generated by Django 3.2.23 on 2024-01-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0004_artist_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
