# Generated by Django 3.2.23 on 2024-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0006_alter_artist_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='sub_titles',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artistapp.Subtitle'),
        ),
    ]
