# Generated by Django 3.2.23 on 2024-01-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0008_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='name',
            field=models.CharField(default='정보', max_length=100),
        ),
        migrations.AlterField(
            model_name='description',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_descriptions', to='artistapp.artist'),
        ),
    ]
