# Generated by Django 3.2.23 on 2024-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0002_person_position'),
        ('artistapp', '0009_auto_20240122_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='artist', to='personapp.Person'),
        ),
    ]
