# Generated by Django 3.2.23 on 2024-01-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0010_artist_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='text_person',
            field=models.TextField(blank=True, null=True),
        ),
    ]
