# Generated by Django 3.2.23 on 2024-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('vocal', '보컬'), ('guitar', '기타'), ('drums', '드럼'), ('bass', '베이스'), ('keyboard', '키보드')], max_length=10),
        ),
    ]
