# Generated by Django 3.2.23 on 2024-01-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribeapp', '0002_auto_20231120_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Per_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Per_subscripton', to='personapp.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Per_subscripton', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'person')},
            },
        ),
    ]
