# Generated by Django 3.2.23 on 2023-11-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20231122_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='writer',
        ),
    ]
