# Generated by Django 3.2.23 on 2023-11-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0006_article_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
    ]
