# Generated by Django 3.2.23 on 2023-11-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0007_remove_article_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
