# Generated by Django 3.2.23 on 2024-01-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0009_article_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
    ]
