# Generated by Django 3.2.23 on 2024-01-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0002_alter_artist_image'),
        ('articleapp', '0010_remove_article_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='artist',
        ),
        migrations.AddField(
            model_name='article',
            name='artist',
            field=models.ManyToManyField(null=True, related_name='article', to='artistapp.Artist'),
        ),
    ]
