# Generated by Django 3.2.23 on 2024-01-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0002_alter_artist_image'),
        ('articleapp', '0011_auto_20240102_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='article', to='artistapp.Artist'),
        ),
    ]
