# Generated by Django 3.2.23 on 2024-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_auto_20240106_1606'),
        ('articleapp', '0012_alter_article_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='project',
        ),
        migrations.AddField(
            model_name='article',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project', to='projectapp.Project'),
        ),
    ]
