# Generated by Django 3.2.23 on 2024-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_auto_20240106_1606'),
        ('articleapp', '0013_auto_20240107_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='article', to='projectapp.Project'),
        ),
    ]
