# Generated by Django 3.2.23 on 2024-01-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0014_alter_article_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
