# Generated by Django 3.2.23 on 2024-01-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0016_rename_is_temporary_article_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hide',
            field=models.BooleanField(default=True),
        ),
    ]
