# Generated by Django 3.2.23 on 2024-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0017_alter_article_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
