# Generated by Django 3.2.23 on 2024-01-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0001_initial'),
        ('articleapp', '0019_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='article', to='personapp.Person'),
        ),
    ]
